sudo: required

services:
- docker

before_install:
- docker build -t vijos/jd4 .

script:
- docker run --privileged
      -v $(readlink -f examples/config.yaml):/root/.config/jd4/config.yaml
      vijos/jd4 /bin/bash -c "source /venv/bin/activate &&
                              python3 -m jd4.integration_test"
